### ISSUE TITLE
pio: command not found

### ISSUE THREAD

**Issue by AnjaBasara** [anchetaWern/predictionio-movierecommendation#1]
Hello, I've found your [Movie Recommendation App tutorial](https://www.sitepoint.com/predictionio-bootstrapping-a-movie-recommendation-app/) which will be useful for my University project, but I'm having problems with PredictionIO Vagrant box. 

I followed your tutorial, cloned the Vagrant file from [this link](https://github.com/PredictionIO/PredictionIO-Vagrant), configured Vagrantfile, and then executed `vagrant up`. The problem is, it doesn't recognize `pio-start-all`. This is the bottom part of the `vagrant up` output:

` default: PredictionIO already installed. Skip installation.`
`default: /tmp/vagrant-shell: line 32: pio-start-all: command not found`
`default: --------------------------------------------------------------------------------`
`default: PredictionIO VM is up!`
`default: You could run 'pio status' inside VM ('vagrant ssh' to VM first) to confirm if PredictionIO is ready.`
`default: IMPORTANT: You still have to start the eventserver manually (inside VM):`
`default: Run: 'pio eventserver --ip 0.0.0.0'`
`default: --------------------------------------------------------------------------------`

At first I didn't see the line `default: /tmp/vagrant-shell: line 32: pio-start-all: command not found` so I continued with the tutorial, downloaded the recommendation template, configured it and after I typed `pio app new MovieRecommendationApp` I got the output:
`bash: pio: command not found`.

After googling I found out that the `pio` command isn't in `$PATH`, but I can't find the `bin` to export it to `$PATH`.

I know this problem isn't directly connected to your app, but the Vagrant itself, but I'm hoping to get your help, since I did everything like in the tutorial. I'm using Vagrant 2.2.4.

**Comment by anchetaWern** [comment]
@AnjaBasara looks like prediction.io is already adopted by Apache. Which makes my tutorial obsolete :( 
Their docs have moved here: http://predictionio.apache.org/install/
And looks like someone has written a tutorial about it here: https://www.freecodecamp.org/news/building-an-recommendation-engine-with-apache-prediction-io-ml-server-aed0319e0d8/
